
language: android
android:
  components:

    - build-tools-23.0.1

    - android-22

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-home
  - export ANDROID_NDK_HOME=$HOME/android-ndk-home

script: ./gradlew build

after_script: cat $HOME/build/billthefarmer/mididriver/build/outputs/lint-results.xml
