language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28

before_install:
  - echo y | sdkmanager "ndk-bundle"

script:
  - ./gradlew build
