language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28

before_install:
  - echo y | sdkmanager "ndk-bundle"
  - export ANDROID_NDK_HOME=$HOME/android-ndk-home
  - pushd $ANDROID_NDK_HOME
  - popd

script:
  - ./gradlew build
